/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgb(var(--primary) / <alpha-value>)",
          900: "rgb(var(--primary-900) / <alpha-value>)",
          800: "rgb(var(--primary-800) / <alpha-value>)",
          700: "rgb(var(--primary-700) / <alpha-value>)",
          600: "rgb(var(--primary-600) / <alpha-value>)",
          500: "rgb(var(--primary-500) / <alpha-value>)",
          400: "rgb(var(--primary-400) / <alpha-value>)",
          300: "rgb(var(--primary-300) / <alpha-value>)",
          200: "rgb(var(--primary-200) / <alpha-value>)",
          100: "rgb(var(--primary-100) / <alpha-value>)",
          50: "rgb(var(--primary-50) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary) / <alpha-value>)",
          900: "rgb(var(--secondary-900) / <alpha-value>)",
          800: "rgb(var(--secondary-800) / <alpha-value>)",
          700: "rgb(var(--secondary-700) / <alpha-value>)",
          600: "rgb(var(--secondary-600) / <alpha-value>)",
          500: "rgb(var(--secondary-500) / <alpha-value>)",
          400: "rgb(var(--secondary-400) / <alpha-value>)",
          300: "rgb(var(--secondary-300) / <alpha-value>)",
          200: "rgb(var(--secondary-200) / <alpha-value>)",
          100: "rgb(var(--secondary-100) / <alpha-value>)",
          50: "rgb(var(--secondary-50) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--success) / <alpha-value>)",
          900: "rgb(var(--success-900) / <alpha-value>)",
          800: "rgb(var(--success-800) / <alpha-value>)",
          700: "rgb(var(--success-700) / <alpha-value>)",
          600: "rgb(var(--success-600) / <alpha-value>)",
          500: "rgb(var(--success-500) / <alpha-value>)",
          400: "rgb(var(--success-400) / <alpha-value>)",
          300: "rgb(var(--success-300) / <alpha-value>)",
          200: "rgb(var(--success-200) / <alpha-value>)",
          100: "rgb(var(--success-100) / <alpha-value>)",
          50: "rgb(var(--success-50) / <alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--danger) / <alpha-value>)",
          900: "rgb(var(--danger-900) / <alpha-value>)",
          800: "rgb(var(--danger-800) / <alpha-value>)",
          700: "rgb(var(--danger-700) / <alpha-value>)",
          600: "rgb(var(--danger-600) / <alpha-value>)",
          500: "rgb(var(--danger-500) / <alpha-value>)",
          400: "rgb(var(--danger-400) / <alpha-value>)",
          300: "rgb(var(--danger-300) / <alpha-value>)",
          200: "rgb(var(--danger-200) / <alpha-value>)",
          100: "rgb(var(--danger-100) / <alpha-value>)",
          50: "rgb(var(--danger-50) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--warning) / <alpha-value>)",
          900: "rgb(var(--warning-900) / <alpha-value>)",
          800: "rgb(var(--warning-800) / <alpha-value>)",
          700: "rgb(var(--warning-700) / <alpha-value>)",
          600: "rgb(var(--warning-600) / <alpha-value>)",
          500: "rgb(var(--warning-500) / <alpha-value>)",
          400: "rgb(var(--warning-400) / <alpha-value>)",
          300: "rgb(var(--warning-300) / <alpha-value>)",
          200: "rgb(var(--warning-200) / <alpha-value>)",
          100: "rgb(var(--warning-100) / <alpha-value>)",
          50: "rgb(var(--warning-50) / <alpha-value>)",
        },
        grey: {
          DEFAULT: "rgb(var(--grey) / <alpha-value>)",
          900: "rgb(var(--grey-900) / <alpha-value>)",
          800: "rgb(var(--grey-800) / <alpha-value>)",
          700: "rgb(var(--grey-700) / <alpha-value>)",
          600: "rgb(var(--grey-600) / <alpha-value>)",
          500: "rgb(var(--grey-500) / <alpha-value>)",
          400: "rgb(var(--grey-400) / <alpha-value>)",
          300: "rgb(var(--grey-300) / <alpha-value>)",
          200: "rgb(var(--grey-200) / <alpha-value>)",
          100: "rgb(var(--grey-100) / <alpha-value>)",
          50: "rgb(var(--grey-50) / <alpha-value>)",
        },
        stroke: {
          50: "rgb(var(--stroke-50) / <alpha-value>)",
          100: "rgb(var(--stroke-100) / <alpha-value>)",
          200: "rgb(var(--stroke-200) / <alpha-value>)",
          300: "rgb(var(--stroke-300) / <alpha-value>)",
          400: "rgb(var(--stroke-400) / <alpha-value>)",
          500: "rgb(var(--stroke-500) / <alpha-value>)",
          600: "rgb(var(--stroke-600) / <alpha-value>)",
        },
        text: {
          dark: "rgb(var(--text-dark) / <alpha-value>)",
          light: "rgb(var(--text-light) / <alpha-value>)",
          primary: "rgb(var(--text-primary) / <alpha-value>)",
          hint: "rgb(var(--text-hint) / <alpha-value>)",
          disabled: "rgb(var(--text-disabled) / <alpha-value>)",
          success: "rgb(var(--text-success) / <alpha-value>)",
          warning: "rgb(var(--text-warning) / <alpha-value>)",
          error: "rgb(var(--text-error) / <alpha-value>)",
        },
      },
      backgroundImage: {
        "grad-001-bg": "var(--grad-001-bg)",
        "grad-002-bg": "var(--grad-002-bg)",
        "grad-005-bg": "var(--grad-005-bg)",
        "grad-007-bg": "var(--grad-007-bg)",
        "grad-008-bg": "var(--grad-008-bg)",
        "grad-010-bg": "var(--grad-010-bg)",
        "grad-12-bg": "var(--grad-12-bg)",
        "grad-009-bg": "var(--grad-009-bg)",
        "grad-011-text": "var(--grad-011-text)",
        "grad-012-bg": "var(--grad-012-bg)",
        "grad-004": "var(--grad-004)",
        "grad-card-1": "var(--grad-card-1)",
        "grad-card-2": "var(--grad-card-2)",
        "grad-card-3": "var(--grad-card-3)",
        "grad-card-4": "var(--grad-card-4)",
        "grad-card-5": "var(--grad-card-5)",
        "grad-card-6": "var(--grad-card-6)",
        "grad-card-7": "var(--grad-card-7)",
        "grad-card-8": "var(--grad-card-8)",
      },
      fontSize: {
        "display-1": ["80px", { lineHeight: "100px", letterSpacing: "0em" }],
        "display-2": ["72px", { lineHeight: "88px", letterSpacing: "0em" }],
        "display-3": ["64px", { lineHeight: "80px", letterSpacing: "0em" }],
        "display-4": ["60px", { lineHeight: "72px", letterSpacing: "0em" }],
        "display-5": ["48px", { lineHeight: "56px", letterSpacing: "0em" }],
        "display-6": ["40px", { lineHeight: "48px", letterSpacing: "0em" }],

        "headline-1": ["40px", { lineHeight: "48px", letterSpacing: "0em" }],
        "headline-2": ["32px", { lineHeight: "40px", letterSpacing: "0em" }],
        "headline-3": ["28px", { lineHeight: "32px", letterSpacing: "0em" }],
        "headline-4": ["24px", { lineHeight: "28px", letterSpacing: "0em" }],
        "headline-5": ["20px", { lineHeight: "24px", letterSpacing: "0em" }],
        "headline-6": ["16px", { lineHeight: "20px", letterSpacing: "0em" }],

        "title-1": ["22px", { lineHeight: "28px", letterSpacing: "0em" }],
        "title-2": ["16px", { lineHeight: "24px", letterSpacing: "0.15em" }],
        "title-3": ["14px", { lineHeight: "20px", letterSpacing: "0.1em" }],

        "label-1": ["14px", { lineHeight: "20px", letterSpacing: "0.1em" }],
        "label-2": ["12px", { lineHeight: "16px", letterSpacing: "0.5em" }],
        "label-3": ["11px", { lineHeight: "16px", letterSpacing: "0.5em" }],

        "body-1": ["16px", { lineHeight: "24px", letterSpacing: "0.5em" }],
        "body-2": ["14px", { lineHeight: "20px", letterSpacing: "0.25em" }],
        "body-3": ["12px", { lineHeight: "16px", letterSpacing: "0.4em" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.3s ease-out forwards",
      },
    },
  },
  plugins: [],
};

